# This file was generated by GoReleaser. DO NOT EDIT.
cask "mcpchecker-agent" do
  name "mcpchecker-agent"
  desc "Agent CLI for interacting with MCP servers"
  homepage "https://github.com/mcpchecker/mcpchecker"
  version "0.0.7"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mcpchecker-agent"

  on_macos do
    on_intel do
      url "https://github.com/mcpchecker/mcpchecker/releases/download/v#{version}/agent-darwin-amd64.zip",
        verified: "github.com/mcpchecker/mcpchecker"
      sha256 "3b845fbb7022beda0a7fea830b6f77878f13ccbe19fdc21dfda3896564606973"
    end
    on_arm do
      url "https://github.com/mcpchecker/mcpchecker/releases/download/v#{version}/agent-darwin-arm64.zip",
        verified: "github.com/mcpchecker/mcpchecker"
      sha256 "9328884e9706a8a368db4cd536a3ce8ccee614ecdb935686285274449f19a7d1"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/mcpchecker/mcpchecker/releases/download/v#{version}/agent-linux-amd64.zip",
        verified: "github.com/mcpchecker/mcpchecker"
      sha256 "99e42231a0e9637c75bb9c1600b2ee2cdb6a7e37014dc1188c2a09cd450b2ff7"
    end
    on_arm do
      url "https://github.com/mcpchecker/mcpchecker/releases/download/v#{version}/agent-linux-arm64.zip",
        verified: "github.com/mcpchecker/mcpchecker"
      sha256 "f25fa226dd6bf8d8e30472ebcebce159bce4c476a4bd98758966044163495cfb"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/agent"]
    end
  end

  # No zap stanza required
end
