# This file was generated by GoReleaser. DO NOT EDIT.
cask "mcpchecker" do
  name "mcpchecker"
  desc "Integration testing framework for your MCP Servers and Agents"
  homepage "https://github.com/mcpchecker/mcpchecker"
  version "0.0.9"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mcpchecker"

  on_macos do
    on_intel do
      url "https://github.com/mcpchecker/mcpchecker/releases/download/v#{version}/mcpchecker-darwin-amd64.zip",
        verified: "github.com/mcpchecker/mcpchecker"
      sha256 "c87715f26845a770fcf6c639b457503579147ccd3b7787a706abd2a79a7b52bd"
    end
    on_arm do
      url "https://github.com/mcpchecker/mcpchecker/releases/download/v#{version}/mcpchecker-darwin-arm64.zip",
        verified: "github.com/mcpchecker/mcpchecker"
      sha256 "9b1980311123fc55971f1b52292a723e435c3e4f4e2a4b8f3ec4d2c7121af457"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/mcpchecker/mcpchecker/releases/download/v#{version}/mcpchecker-linux-amd64.zip",
        verified: "github.com/mcpchecker/mcpchecker"
      sha256 "21b856427e5e7d5c990976e56522571c1de88c079c1a8ca409a815a5dd11bf7e"
    end
    on_arm do
      url "https://github.com/mcpchecker/mcpchecker/releases/download/v#{version}/mcpchecker-linux-arm64.zip",
        verified: "github.com/mcpchecker/mcpchecker"
      sha256 "0bce3306a68a84a834c69ec9e8bf6eb64607bfadcc5f020061308fa00997b870"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mcpchecker"]
    end
  end

  # No zap stanza required
end
