# This file was generated by GoReleaser. DO NOT EDIT.
cask "mcpchecker-agent" do
  name "mcpchecker-agent"
  desc "Agent CLI for interacting with MCP servers"
  homepage "https://github.com/mcpchecker/mcpchecker"
  version "0.0.9"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mcpchecker-agent"

  on_macos do
    on_intel do
      url "https://github.com/mcpchecker/mcpchecker/releases/download/v#{version}/agent-darwin-amd64.zip",
        verified: "github.com/mcpchecker/mcpchecker"
      sha256 "c8079c4254f5ffae452188d3c3ee7d886a74ff893b54beb67f6875e8bd564fac"
    end
    on_arm do
      url "https://github.com/mcpchecker/mcpchecker/releases/download/v#{version}/agent-darwin-arm64.zip",
        verified: "github.com/mcpchecker/mcpchecker"
      sha256 "936e76afea6cca821125c7435b4a169f882f4558ccc052dcd585a030e8c95a7e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/mcpchecker/mcpchecker/releases/download/v#{version}/agent-linux-amd64.zip",
        verified: "github.com/mcpchecker/mcpchecker"
      sha256 "534a0e7e32ccd1a666df250e8b707416d348c621070ee5bf6d6e0ffc4ab816fe"
    end
    on_arm do
      url "https://github.com/mcpchecker/mcpchecker/releases/download/v#{version}/agent-linux-arm64.zip",
        verified: "github.com/mcpchecker/mcpchecker"
      sha256 "0be10a50196646e5758cddf79f56e416b5933aed6e67f0ecc7926f9b3de23aa7"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/agent"]
    end
  end

  # No zap stanza required
end
