# This file was generated by GoReleaser. DO NOT EDIT.
cask "mcpchecker-agent" do
  version "0.0.13"

  on_macos do
    on_intel do
      url "https://github.com/mcpchecker/mcpchecker/releases/download/v#{version}/agent-darwin-amd64.zip",
        verified: "github.com/mcpchecker/mcpchecker"
      sha256 "12d811b29a59ba4fa3cc41da9dd95dfdc28a6ab74fe565f7d319251edec07130"
    end
    on_arm do
      url "https://github.com/mcpchecker/mcpchecker/releases/download/v#{version}/agent-darwin-arm64.zip",
        verified: "github.com/mcpchecker/mcpchecker"
      sha256 "b9ab69fcc8dce1b18d16502e96c72bc93e8c270049f68751726b66e48efa486f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/mcpchecker/mcpchecker/releases/download/v#{version}/agent-linux-amd64.zip",
        verified: "github.com/mcpchecker/mcpchecker"
      sha256 "a1541626254bd031129336352092c00710dc585f3fb53b1567098e408c856e16"
    end
    on_arm do
      url "https://github.com/mcpchecker/mcpchecker/releases/download/v#{version}/agent-linux-arm64.zip",
        verified: "github.com/mcpchecker/mcpchecker"
      sha256 "d1fc07aca8678e91ef6d38768c432f9adae6750794c96f60384574692bf68314"
    end
  end

  name "mcpchecker-agent"
  desc "Agent CLI for interacting with MCP servers"
  homepage "https://github.com/mcpchecker/mcpchecker"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mcpchecker-agent"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/agent"]
    end
  end

  # No zap stanza required

end
