# This file was generated by GoReleaser. DO NOT EDIT.
cask "mcpchecker" do
  version "0.0.13"

  on_macos do
    on_intel do
      url "https://github.com/mcpchecker/mcpchecker/releases/download/v#{version}/mcpchecker-darwin-amd64.zip",
        verified: "github.com/mcpchecker/mcpchecker"
      sha256 "0a99e1151ca3fcd6aa84ac436b6ce9f9875b256d23d080c6e87c197ea6fd7b1a"
    end
    on_arm do
      url "https://github.com/mcpchecker/mcpchecker/releases/download/v#{version}/mcpchecker-darwin-arm64.zip",
        verified: "github.com/mcpchecker/mcpchecker"
      sha256 "7d7762afbab985c0aa757ad3ad28b40a3b9ded34bebac019e8c06e246232a6ea"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/mcpchecker/mcpchecker/releases/download/v#{version}/mcpchecker-linux-amd64.zip",
        verified: "github.com/mcpchecker/mcpchecker"
      sha256 "c2ccfd34a7098c29fd197d54be7f2be85c07a3241e557bd53a761cd4d007c5b1"
    end
    on_arm do
      url "https://github.com/mcpchecker/mcpchecker/releases/download/v#{version}/mcpchecker-linux-arm64.zip",
        verified: "github.com/mcpchecker/mcpchecker"
      sha256 "144ad6e1918af43753afb0090b2c360a55f4c9c69bf0be7fb85741ddaa2ac048"
    end
  end

  name "mcpchecker"
  desc "Integration testing framework for your MCP Servers and Agents"
  homepage "https://github.com/mcpchecker/mcpchecker"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mcpchecker"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mcpchecker"]
    end
  end

  # No zap stanza required

end
