# This file was generated by GoReleaser. DO NOT EDIT.
cask "mcpchecker" do
  name "mcpchecker"
  desc "Integration testing framework for your MCP Servers and Agents"
  homepage "https://github.com/mcpchecker/mcpchecker"
  version "0.0.11"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mcpchecker"

  on_macos do
    on_intel do
      url "https://github.com/mcpchecker/mcpchecker/releases/download/v#{version}/mcpchecker-darwin-amd64.zip",
        verified: "github.com/mcpchecker/mcpchecker"
      sha256 "27e2e9fd2b91ffe1ed822a1acc5c1f470bb67358c661944ea9e45a0e4d926033"
    end
    on_arm do
      url "https://github.com/mcpchecker/mcpchecker/releases/download/v#{version}/mcpchecker-darwin-arm64.zip",
        verified: "github.com/mcpchecker/mcpchecker"
      sha256 "fd1a2671e673c79b5ed108bd65973e05168c4e44a2ed776fde44ed25b3f664a6"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/mcpchecker/mcpchecker/releases/download/v#{version}/mcpchecker-linux-amd64.zip",
        verified: "github.com/mcpchecker/mcpchecker"
      sha256 "6b7311c1809babfed36586f34d946c606ca418e4410494f4d739312167055b80"
    end
    on_arm do
      url "https://github.com/mcpchecker/mcpchecker/releases/download/v#{version}/mcpchecker-linux-arm64.zip",
        verified: "github.com/mcpchecker/mcpchecker"
      sha256 "f576b62411c58da99a65dd085aaa67c32abddbff5ab90a4ad099119a50bc8038"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mcpchecker"]
    end
  end

  # No zap stanza required
end
